server:
  port: 8090
spring:
  cloud:
    gateway:
      enabled: true
      default-filters:
        - AddResponseHeader=source, jack
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
    nacos:
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  application:
    name: api-gateway-consumer
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
# dubbo 配置
dubbo:
  application:
    name: api-gateway-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848