server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, jack
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/**
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: gateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
# dubbo 配置
dubbo:
  application:
    name: api-gateway-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
